<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class task_sub_template_Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ["task_main_id" => 0, "NAME" => "Di chuyển tới mũi tên chỉ dẫn", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 0, "NAME" => "Hãy đi đến nhà ông %2 ở bên phải", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-2", "map" => "-2"],
            ["task_main_id" => 0, "NAME" => "Nói chuyện với ông %2", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-2", "map" => "-2"],
            ["task_main_id" => 0, "NAME" => "Mở rương đồ", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "3", "map" => "-2"],
            ["task_main_id" => 0, "NAME" => "Thu hoạch đậu thần", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "4", "map" => "-2"],
            ["task_main_id" => 0, "NAME" => "Báo cáo với ông %2", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-2", "map" => "-2"],
            ["task_main_id" => 1, "NAME" => "Đánh ngã 5 mộc nhân", "max_count" => "5", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 1, "NAME" => "Báo cáo với ông %2", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-2", "map" => "-2"],
            ["task_main_id" => 2, "NAME" => "Tiêu diệt 10 %4", "max_count" => "10", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-3"],
            ["task_main_id" => 2, "NAME" => "Báo cáo với ông %2", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-2", "map" => "-2"],
            ["task_main_id" => 3, "NAME" => "Sử dụng tiềm năng", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 3, "NAME" => "Đi khám phá vật thể lạ", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-4"],
            ["task_main_id" => 3, "NAME" => "Báo cáo với ông %2", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-2", "map" => "-2"],
            ["task_main_id" => 4, "NAME" => "Tiêu diệt 10 %4 mẹ", "max_count" => "10", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-5"],
            ["task_main_id" => 4, "NAME" => "Báo cáo với ông %2", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-2", "map" => "-2"],
            ["task_main_id" => 5, "NAME" => "Đạt 20k sức mạnh", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 5, "NAME" => "Đạt 35k sức mạnh", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 5, "NAME" => "Đạt 60k sức mạnh", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 5, "NAME" => "Quay về nhà báo cáo", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-2", "map" => "-2"],
            ["task_main_id" => 6, "NAME" => "Tìm đến trạm tàu vũ trụ", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-6"],
            ["task_main_id" => 6, "NAME" => "Nói chuyện với %7", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-3", "map" => "-6"],
            ["task_main_id" => 7, "NAME" => "Lên đường tìm kiếm lũ %9", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-7"],
            ["task_main_id" => 7, "NAME" => "Diệt 10 con %9", "max_count" => "10", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-7"],
            ["task_main_id" => 7, "NAME" => "Trả nhiệm vụ cho %7", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-3", "map" => "-6"],
            ["task_main_id" => 8, "NAME" => "Quay về %1", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 8, "NAME" => "Hỏi thăm sức khỏe %8", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-4", "map" => "-8"],
            ["task_main_id" => 8, "NAME" => "Quay về kể lại cho ông %2", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-2", "map" => "-2"],
            ["task_main_id" => 9, "NAME" => "Lên đường", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-9"],
            ["task_main_id" => 9, "NAME" => "Chào hỏi %10", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-5", "map" => "-9"],
            ["task_main_id" => 1, "NAME" => " Đạt 200k sức mạnh", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 1, "NAME" => " Diệt 30 con %12", "max_count" => "30", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-9"],
            ["task_main_id" => 1, "NAME" => " Báo cáo với %10", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-5", "map" => "-9"],
            ["task_main_id" => 1, "NAME" => " Kết bạn với 1 người Trái Đất", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 1, "NAME" => " Kết bạn với 1 người Namếc", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 1, "NAME" => " Kết bạn với 1 người Xayda", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 1, "NAME" => " Báo cáo với %10", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-5", "map" => "-9"],
            ["task_main_id" => 1, "NAME" => " Đi về nhà ông %2", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-2"],
            ["task_main_id" => 1, "NAME" => " Nói chuyện - xin phép gia nhập bang hội", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-2", "map" => "-2"],
            ["task_main_id" => 1, "NAME" => " Báo cáo lại cho %10", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-5", "map" => "-9"],
            ["task_main_id" => 1, "NAME" => " Tạo/gia nhập bang hội có 2 thành viên", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 1, "NAME" => " Báo cáo cho %10", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-5", "map" => "-9"],
            ["task_main_id" => 1, "NAME" => " Tiêu diệt 25 con heo rừng", "max_count" => "25", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "27"],
            ["task_main_id" => 1, "NAME" => " Tiêu diệt 25 con heo da xanh", "max_count" => "25", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "31"],
            ["task_main_id" => 1, "NAME" => " Tiêu diệt 25 con heo xayda", "max_count" => "25", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "35"],
            ["task_main_id" => 1, "NAME" => " Quay về %11 báo cáo nhiệm vụ", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-5", "map" => "-9"],
            ["task_main_id" => 1, "NAME" => " Tiêu diệt 50 bulon", "max_count" => "50", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "30"],
            ["task_main_id" => 1, "NAME" => " Tiêu diệt 50 ukulele", "max_count" => "50", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "34"],
            ["task_main_id" => 1, "NAME" => " Tiêu diệt 50 quỷ mập", "max_count" => "50", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "38"],
            ["task_main_id" => 1, "NAME" => " Quay về %11 báo cáo nhiệm vụ", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-5", "map" => "-9"],
            ["task_main_id" => 1, "NAME" => " Tiêu diệt 1 tambourine", "max_count" => "20", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "6"],
            ["task_main_id" => 1, "NAME" => " Tiêu diệt 1 drum", "max_count" => "20", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "10"],
            ["task_main_id" => 1, "NAME" => " Tiêu diệt 1 akkuman", "max_count" => "20", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "19"],
            ["task_main_id" => 1, "NAME" => " Quay về %11 báo cáo nhiệm vụ", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-5", "map" => "-9"],
            ["task_main_id" => 1, "NAME" => " Tới tp.Vegeta", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "19"],
            ["task_main_id" => 1, "NAME" => " Nói chuyện với Cui", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "12", "map" => "19"],
            ["task_main_id" => 1, "NAME" => " Tiêu diệt 500 nappa", "max_count" => "500", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 1, "NAME" => " Tiêu diệt 400 soldier", "max_count" => "400", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 1, "NAME" => " Tiêu diệt 300 appule", "max_count" => "300", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 1, "NAME" => " Tiêu diệt 200 raspberry", "max_count" => "200", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 1, "NAME" => " Tiêu diệt 100 thằn lằn xanh", "max_count" => "100", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 1, "NAME" => " Trả nhiệm vụ cho Cui", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "12", "map" => "19"],
            ["task_main_id" => 1, "NAME" => " Tiêu diệt Kuku", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 1, "NAME" => " Tiêu diệt Mập đầu đinh", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 1, "NAME" => " Tiêu diệt Rambo", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 1, "NAME" => " Trả nhiệm vụ cho Cui", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "12", "map" => "19"],
            ["task_main_id" => 2, "NAME" => " Đạt 600 tr sức mạnh", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 2, "NAME" => " Tiêu diệt số 4", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 2, "NAME" => " Tiêu diệt số 3", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 2, "NAME" => " Tiêu diệt số 2", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 2, "NAME" => " Tiêu diệt số 1", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 2, "NAME" => " Tiêu diệt tiểu đội trưởng", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 2, "NAME" => " Báo cáo với Cui", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "12", "map" => "19"],
            ["task_main_id" => 2, "NAME" => " Đạt 2 tỷ sức mạnh", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 2, "NAME" => " Tiêu diệt Fide đại ca 1", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 2, "NAME" => " Tiêu diệt Fide đại ca 2", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 2, "NAME" => " Tiêu diệt Fide đại ca 3", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 2, "NAME" => " Báo cáo với Cui", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "12", "map" => "19"],
            ["task_main_id" => 2, "NAME" => " Tìm gặp Bunma tại tương lai", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "37", "map" => "102"],
            ["task_main_id" => 2, "NAME" => " Đến điểm hẹn tìm Rôbốt sát thủ", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "93"],
            ["task_main_id" => 2, "NAME" => " Làm thịt Android 19", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 2, "NAME" => " Cháo hành lão Dr.Korê", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 2, "NAME" => " Trả nhiệm vụ cho Bunma", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "37", "map" => "102"],
            ["task_main_id" => 2, "NAME" => " Đến điểm gặp", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "97"],
            ["task_main_id" => 2, "NAME" => " Tiêu diệt Poc", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 2, "NAME" => " Tiêu diệt Pic", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "97"],
            ["task_main_id" => 2, "NAME" => " Tiêu diệt King Kong", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "97"],
            ["task_main_id" => 2, "NAME" => " Trả nhiệm vụ cho Bunma", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "37", "map" => "102"],
            ["task_main_id" => 2, "NAME" => " Lên đường tới thị trấn Ginder", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "100"],
            ["task_main_id" => 2, "NAME" => " Tiêu diệt Xên bọ hung cấp 1", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 2, "NAME" => " Tiêu diệt Xên bọ hung cấp 2", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 2, "NAME" => " Tiêu diệt Xên hoàn thiện", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 2, "NAME" => " Trả nhiệm vụ cho Bunma", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "37", "map" => "102"],
            ["task_main_id" => 2, "NAME" => " Tiêu Diệt Xên 1", "max_count" => "1000", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 2, "NAME" => " Tiêu Diệt Xên 2", "max_count" => "1000", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 2, "NAME" => " Tiêu Diệt Xên 3", "max_count" => "1000", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 2, "NAME" => " Tiêu Diệt Xên 4", "max_count" => "1000", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 2, "NAME" => " Tiêu Diệt Xên 5", "max_count" => "1000", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 2, "NAME" => " Trả nhiệm vụ cho Bunma", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "37", "map" => "102"],
            ["task_main_id" => 2, "NAME" => " Tiêu Diệt Xên 6", "max_count" => "1000", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 2, "NAME" => " Tiêu Diệt Xên 7", "max_count" => "1000", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 2, "NAME" => " Tiêu Diệt Xên 8", "max_count" => "1000", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 2, "NAME" => " Tìm Capsule", "max_count" => "1000", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 2, "NAME" => " Trả nhiệm vụ cho Bunma", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "37", "map" => "102"],
            ["task_main_id" => 2, "NAME" => " Kết bạn với 1 người trái đất", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 2, "NAME" => " Kết bạn với 1 người Namec", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 2, "NAME" => " Kết bạn với 1 người Xayda", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 2, "NAME" => " Tìm 2s Ở Võ Đài Xên", "max_count" => "10", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 2, "NAME" => " Trả nhiệm vụ cho Bunma", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "37", "map" => "102"],
            ["task_main_id" => 2, "NAME" => " Đến võ đài xên bọ hung", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "103"],
            ["task_main_id" => 2, "NAME" => " Tiêu Diệt Xên Con", "max_count" => "30", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "103"],
            ["task_main_id" => 2, "NAME" => " Tiêu Diệt Siêu Bọ Hung", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 2, "NAME" => " Tiêu Diệt Siêu Bọ Hung 2", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 2, "NAME" => " Tiêu Diệt Siêu Bọ Hung 3", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 2, "NAME" => " Trả nhiệm vụ cho Bunma", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "37", "map" => "102"],
            ["task_main_id" => 2, "NAME" => " Tiêu Diệt Tai Tím", "max_count" => "1000", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 2, "NAME" => " Tiêu Diệt Kabo", "max_count" => "1500", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 2, "NAME" => " Tiêu Diệt Abo", "max_count" => "2000", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 2, "NAME" => " Tiêu Diệt Da Xanh", "max_count" => "2500", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 2, "NAME" => " Trả nhiệm vụ cho Bunma", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "37", "map" => "102"],
            ["task_main_id" => 3, "NAME" => " Tiêu Diệt Xuka", "max_count" => "20", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 3, "NAME" => " Tiêu Diệt Chaien", "max_count" => "20", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 3, "NAME" => " Tiêu Diệt Doraemon", "max_count" => "20", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 3, "NAME" => " Tiêu Diệt Nobita", "max_count" => "20", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 3, "NAME" => " Tiêu Diệt Xeko", "max_count" => "20", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 3, "NAME" => " Trả nhiệm vụ cho Bunma", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "37", "map" => "102"],
            ["task_main_id" => 3, "NAME" => " Tìm Chiếc Nhẫn Thời Không Ở Black Goku", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 3, "NAME" => " Tìm Kiếm Z Ở Super Black Rose", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 3, "NAME" => " Tìm Rùa Con Ở Zamas Kaioshin", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 3, "NAME" => " Tìm Siêu Thần Thủy Ở Thần Zamas Tối Thượng", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "-1"],
            ["task_main_id" => 3, "NAME" => " Trả nhiệm vụ cho Bunma", "max_count" => "1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "37", "map" => "102"],
            ["task_main_id" => 3, "NAME" => " Chúc cu em làm nvu lần sau nhé", "max_count" => "-1", "notify" => "Hay lắm! Đúng là con trai của ta!!!!", "npc_id" => "-1", "map" => "0"]
        ];
        foreach ($data as $key => $value) {
            \DB::table('task_sub_template')->insert([
                'task_main_id' => $value['task_main_id'],
                'NAME' => $value['NAME'],
                'max_count' => $value['max_count'],
                'notify' => $value['notify'],
                'npc_id' => $value['npc_id'],
                'map' => $value['map'],
            ]);
        }
    }
}